#!/bin/bash
#  abuild.sh
#  
#
#  Created by n-d-k on 10/6/19.
#  Sample of Clover Auto Daily Build Using Travis Ci
#
CLOVER_GIT_URL="https://github.com/CloverHackyColor/CloverBootloader.git"
GIT_DIR="Build"
mkdir $GIT_DIR
git clone $CLOVER_GIT_URL $GIT_DIR

R_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
if [[ $R_TAG == *"-"* ]]; then
    IS_PR_TAG=true
    SHORT_COMMIT=${R_TAG:-7}
    echo "Short Hash: $SHORT_COMMIT"
else
    IS_PR_TAG=false
fi
    
echo "Our tag: $R_TAG"
cd $GIT_DIR

CLOVER_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
CLOVER_TAG_COMMIT=$(git rev-list -n 1 $CLOVER_TAG)
echo "Clover tag: $CLOVER_TAG Commit: $CLOVER_TAG_COMMIT"

LAST_COMMIT=$(git log -n 1 --pretty=format:'%H')
LAST_COMMIT_MESSAGE=$(git log --pretty='format:%Creset%s' --no-merges -1)
echo "Last Clover commit message: $LAST_COMMIT_MESSAGE Hash: ${LAST_COMMIT:0:7}"

[[ "$CLOVER_TAG_COMMIT" == "$LAST_COMMIT" ]] && PRE_RELEASE=false || PRE_RELEASE=true; CLOVER_TAG="$CLOVER_TAG_${LAST_COMMIT:0:7}"

echo "Pre-release : $PRE_RELEASE"

if [[ "$CLOVER_TAG" == "$R_TAG" ]]; then
    echo "Build is up to date!"
    exit 0
else
    echo "Need new build!"
    exit 0
    #./buildme XCODE8 travis
fi
