#!/bin/bash
#  abuild.sh
#  
#
#  Created by n-d-k on 10/6/19.
#  Sample of Clover Auto Daily Build Using Travis Ci
#
CLOVER_GIT_URL="https://github.com/CloverHackyColor/CloverBootloader.git"
GIT_DIR="Build"
mkdir $GIT_DIR
git clone $CLOVER_GIT_URL $GIT_DIR
R_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))

if [[ "$R_TAG" == *"_"* ]]; then
    IS_PR_TAG=true
    SHORT_COMMIT=${R_TAG: -7}
    RR_TAG=${R_TAG:0:4}
    echo "Our tag: $RR_TAG Short Hash: $SHORT_COMMIT"
else
    IS_PR_TAG=false
    RR_TAG=$R_TAG
fi

#=================== Clover repo section ==================
cd $GIT_DIR
LAST_GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
GIT_TAG_COMMIT=$(git rev-list -n 1 $LAST_GIT_TAG)
LAST_GIT_COMMIT=$(git log -n 1 --pretty=format:'%H')
LAST_GIT_COMMIT_MESSAGE=$(git log --pretty='format:%Creset%s' --no-merges -1)

if [[ "$GIT_TAG_COMMIT" == "$LAST_GIT_COMMIT" ]]; then
    PRE_RELEASE=false
else
    # Make sure we compile against the right commit and skipping the release one
    if [[ "$RR_TAG" != "$LAST_GIT_TAG" ]]; then
        git checkout $GIT_TAG_COMMIT
    else
        PRE_RELEASE=true
        LAST_GIT_TAG="${LAST_GIT_TAG}_${LAST_GIT_COMMIT:0:7}"
    fi
fi

echo $LAST_GIT_TAG >> "TAG"
echo $PRE_RELEASE >> "PRERELEASE"
echo "Our current tag: $R_TAG"
echo "Clover current tag: $LAST_GIT_TAG"


if [[ "$LAST_GIT_TAG" == "$R_TAG" ]]; then
    echo "Build is up to date!"
    exit 0
else
    echo "Need new build!"
    #./buildme XCODE8 travis
fi
